fix: fix output

diff --git a/.github/workflows/_prepare-stage.yml b/.github/workflows/_prepare-stage.yml
--- a/.github/workflows/_prepare-stage.yml
+++ b/.github/workflows/_prepare-stage.yml
@@ -25,11 +25,11 @@ jobs:
         echo "Working dir: $(pwd)"
         echo "PATH: $PATH"
         echo "ENV: $(env)"
-        echo "$(ls /venv)"
-        echo "Checking /venv:"
-        echo "Checking /venv (if it exists):"
-        ls -la /venv || echo "/venv not found"
-        ls -d /venv/*
+        echo "$(ls /opt/venv)"
+        echo "Checking /opt/venv:"
+        echo "Checking /opt/venv (if it exists):"
+        ls -la /opt/venv || echo "/opt/venv not found"
+        ls -d /opt/venv/*
     - name: Prepare | job-semver-next
       id: job-semver-next
       run: |
