fix: fixes

diff --git a/.github/workflows/_report-stage.yml b/.github/workflows/_report-stage.yml
--- a/.github/workflows/_report-stage.yml
+++ b/.github/workflows/_report-stage.yml
@@ -28,7 +28,13 @@ jobs:
       env:
         SARIF_REPORT_FULL_PATH: "./code-quality-report.sarif"
       run: |
-        if [[ -f ${SARIF_REPORT_FULL_PATH} ]]; then sarif codeclimate ${SARIF_REPORT_FULL_PATH} || RETURN=$?; else echo "ERROR - File not found ${SARIF_REPORT_FULL_PATH}"; exit 1; fi
+        if [[ -f ${SARIF_REPORT_FULL_PATH} ]]
+        then
+          sarif codeclimate ${SARIF_REPORT_FULL_PATH} || RETURN=$?
+        else
+          echo "❌ Error: File not found ${SARIF_REPORT_FULL_PATH}"
+          exit 1
+        fi
         if [[ 0 == $RETURN ]]; then echo "Return code $RETURN matches expected return"; exit 0; fi
         exit $RETURN
 
diff --git a/.github/workflows/_test-stage.yml b/.github/workflows/_test-stage.yml
--- a/.github/workflows/_test-stage.yml
+++ b/.github/workflows/_test-stage.yml
@@ -104,6 +104,14 @@ jobs:
     - name: Test | job-ansible-tox-sanity
       id: job-ansible-tox-sanity
       run: |
+        export ANSIBLE_COLLECTIONS_PATH=./.ansible/collections
+        COLLECTION_INSTALL_PATH=$( \
+          ansible-galaxy collection install --force . | \
+          grep "Installing" | \
+          awk -F "'" '{ print $4 }' \
+        )
+        export COLLECTION_DIR=${COLLECTION_INSTALL_PATH}
+        ansible-galaxy collection list
         tox --verbose --listenvs-all
         tox
   job-ansible-tox-integration:
@@ -125,5 +133,19 @@ jobs:
     - name: Test | job-ansible-tox-integration
       id: job-ansible-tox-integration
       run: |
-        tox --ansible --conf tox-ansible.ini list
-        tox --ansible --conf tox-ansible.ini
+        export ANSIBLE_COLLECTIONS_PATH=./.ansible/collections
+        COLLECTION_INSTALL_PATH=$( \
+          ansible-galaxy collection install --force . | \
+          grep "Installing" | \
+          awk -F "'" '{ print $4 }' \
+        )
+        export COLLECTION_DIR=${COLLECTION_INSTALL_PATH}
+        ansible-galaxy collection list
+        if [ -f tox-ansible.ini ]
+        then
+          tox --ansible --conf tox-ansible.ini list
+          tox --ansible --conf tox-ansible.ini
+        else
+          echo "❌ Error: File not found tox-ansible.ini"
+          exit 1
+        fi
